### ISSUE TITLE
Incompatible with pydantic 2

### ISSUE THREAD

**Issue by tavianator** [pyodide/sphinx-js-fork#35]
First of all, thanks for creating this fork!  I just used it for https://github.com/microsoft/bistring, and the only trouble I had was this error:

> ```
>   File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.11/site-packages/sphinx_js/__init__.py", line 8, in <module>
>     from .directives import (
>   File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.11/site-packages/sphinx_js/directives.py", line 21, in <module>
>     from .renderers import AutoAttributeRenderer, AutoClassRenderer, AutoFunctionRenderer
>   File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.11/site-packages/sphinx_js/renderers.py", line 31, in <module>
>     from .typedoc import Analyzer as TsAnalyzer
>   File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.11/site-packages/sphinx_js/typedoc.py", line 765, in <module>
>     cls.update_forward_refs()
>   File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.11/site-packages/typing_extensions.py", line 2562, in wrapper
>     return __arg(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.11/site-packages/pydantic/main.py", line 1196, in update_forward_refs
>     cls.model_rebuild(force=True)
>   File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.11/site-packages/pydantic/main.py", line 450, in model_rebuild
>     _model_construction.unpack_lenient_weakvaluedict(cls.__pydantic_parent_namespace__) or {}
>                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/tavianator/.local/share/virtualenvs/docs-BrgkGiab/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 205, in __getattr__
>     raise AttributeError(item)
> AttributeError: __pydantic_parent_namespace__
> ```

Eventually I figured out that I needed to `pipenv install "pydantic<2.0"`.

**Comment by hoodmane** [comment]
Thanks!
